// <auto-generated />
namespace Inventory_Mangement_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IMS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IMS));
        
        string IMigrationMetadata.Id
        {
            get { return "201710030948083_IMS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
